### ISSUE TITLE
Error from server (BadRequest)

### ISSUE THREAD

**Issue by siriaodao** [rootsongjc/follow-me-install-kubernetes-cluster#2]
kubectl logs po/kube-dns-4208593536-l67h8  -n kube-system

Error from server (BadRequest): a container name must be specified for pod kube-dns-4208593536-l67h8, choose one of: [kubedns dnsmasq sidecar]

**Comment by rootsongjc** [comment]
Use `-c` the choose the specific container in pod.
For example:
```
kubectl logs po/kube-dns-4208593536-l67h8 -n kube-system -c kubedns
```
