### ISSUE TITLE
Kubelet: cannot create certificate signing request: the server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by flameyucong** [rootsongjc/follow-me-install-kubernetes-cluster#3]
-- Unit kubelet.service has begun starting up.
May 19 10:27:44 k8s-node4 kubelet[4103]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
May 19 10:27:44 k8s-node4 kubelet[4103]: I0519 10:27:44.450033    4103 feature_gate.go:144] feature gates: map[]
May 19 10:27:44 k8s-node4 kubelet[4103]: error: failed to run Kubelet: cannot create certificate signing request: the server has asked for the client to provide credentials (post certificatesigningrequests.c
May 19 10:27:44 k8s-node4 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
May 19 10:27:44 k8s-node4 systemd[1]: Unit kubelet.service entered failed state.
May 19 10:27:44 k8s-node4 systemd[1]: kubelet.service failed.
May 19 10:27:44 k8s-node4 systemd[1]: kubelet.service holdoff time over, scheduling restart.
May 19 10:27:44 k8s-node4 systemd[1]: Started Kubernetes Kubelet Server.
-- Subject: Unit kubelet.service has finished start-up

**Comment by rootsongjc** [comment]
Hi，本文档已经停止更新了，很多错误也没有及时修正，所有内容已经迁移到了[kubernetes-handbook](https://github.com/rootsongjc/kubernetes-handbook)中，请参考该文档的[在CentOS中安装kubernetes集群部分](https://github.com/rootsongjc/kubernetes-handbook/blob/master/deploy/centos/install-kbernetes1.6-on-centos.md)，希望能对你有帮助。
